inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - ./lib/not_so_great_expectations.rb
  - ./lib/even_worse_expectations.rb
  - ./lib/to_kill_a_mocking_lib.rb

AllCops:
  NewCops: enable
  ExtraDetails: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  Include:
    - 'spec*/**/*.rb'

Metrics:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/BlockDelimiters:
  Exclude: ['test/**/*']

Style/DoubleNegation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals: # A lot of the numbers are object IDs, file sizes, or date times.
  Enabled: false

Lint/MissingSuper: # When using method_missing, fall back on super.
  Enabled: false

Style/MissingRespondToMissing: # When using method_missing, define respond_to_missing?.
  Enabled: false

Style/AccessModifierDeclarations: # private should not be inlined in method definitions.
  Enabled: false

Naming/MemoizedInstanceVariableName: # Memoized variable does not match method name.
  Enabled: false

Security/YAMLLoad: # Using YAML.safe_load over YAML.load produced some spec failures
  Enabled: false

Style/HashTransformValues: # Prefer transform_values over Hash[_.map {...}].
  Enabled: false
