inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - ./lib/not_so_great_expectations.rb
  - ./lib/even_worse_expectations.rb
  - ./lib/to_kill_a_mocking_lib.rb

AllCops:
  NewCops: enable
  ExtraDetails: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  Include:
    - 'spec*/**/*'

Minitest:
  Include:
    - '**/test/**/*'
    - '**/*_test.rb'
    - 'spec*/**/*'

Metrics:
  Enabled: false

Layout:
  Enabled: false

Lint:
  Enabled: false

Naming:
  Enabled: false

Style:
  Enabled: false
